definitions:
  steps:
    - step: &normalize
        script:
          - composer install
          - composer normalize --dry-run
        caches:
          - composer
    - step: &lint
        script:
          - composer install
          - ./vendor/bin/parallel-lint --no-colors --no-progress --checkstyle src > checkstyle-lint.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.5.1
            variables:
              CHECKSTYLE_RESULT_PATTERN: '.*/checkstyle-lint.xml$'
              CHECKSTYLE_REPORT_TITLE: 'Lint'
              CHECKSTYLE_REPORT_ID: 'lint'
        caches:
          - composer
    - step: &ecs
        script:
          - composer install
          - ./vendor/bin/ecs --no-progress-bar --no-interaction --no-ansi --output-format=checkstyle check > checkstyle-ecs.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.5.1
            variables:
              CHECKSTYLE_RESULT_PATTERN: '.*/checkstyle-ecs.xml$'
              CHECKSTYLE_REPORT_TITLE: 'Easy Coding Standard'
              CHECKSTYLE_REPORT_ID: 'ECS'
        caches:
          - composer
    - step: &phpstan
        script:
          - composer install
          - ./vendor/bin/phpstan --no-progress --no-ansi --error-format=checkstyle > checkstyle-phpstan.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.5.1
            variables:
              CHECKSTYLE_RESULT_PATTERN: '.*/checkstyle-phpstan.xml$'
              CHECKSTYLE_REPORT_TITLE: 'PHPStan'
              CHECKSTYLE_REPORT_ID: 'phpstan'
        caches:
          - composer
    - step: &rector
        script:
          - composer install
          - ./vendor/bin/rector process --dry-run --no-ansi --no-progress-bar
        caches:
          - composer
    - step: &phpunit
        script:
          - composer install
          - ./vendor/bin/phpunit --no-progress
        caches:
          - composer

pipelines:
  default:
    - parallel:
        - step:
            <<: *normalize
            name: PHP 8.1 Composer Normalize
            image: 'integerhub/php:8.1-fpm-local'
        - step:
            <<: *lint
            name: PHP 8.1 Lint
            image: 'integerhub/php:8.1-fpm-local'
        - step:
            <<: *ecs
            name: PHP 8.1 ECS
            image: 'integerhub/php:8.1-fpm-local'
        - step:
            <<: *phpstan
            name: PHP 8.1 PHPStan
            image: 'integerhub/php:8.1-fpm-local'
        - step:
            <<: *rector
            name: PHP 8.1 Rector
            image: 'integerhub/php:8.1-fpm-local'
        - step:
            <<: *phpunit
            name: PHP 8.1 PHPUnit
            image: 'integerhub/php:8.1-fpm-local'
